name: Audit Check

on:
  workflow_call:

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - name: Setup
      uses: ./.github/workflows/jobs/setup.yml

    - name: Run npm audit
      needs: setup
      run: npm audit
