name: Format Check

on:
  workflow_call:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Setup
      uses: ./.github/workflows/jobs/setup.yml

    - name: Run Prettier
      needs: setup
      run: npm run format
