name: Setup Environment

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ vars.DEFAULT_NODE_VERSION }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

