name: Build Application

on:
  workflow_call:

job:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup
      uses: ./.github/actions/setup.yml

    - name: Build Application
      needs: setup
      run: npm run build
