name: Check for outdated dependencies

on:
  workflow_call:

jobs:
  outdated:
    runs-on: ubuntu-latest

    steps:
    - name: Setup
      uses: ./.github/actions/setup.yml

    - name: Check for Outdated Dependencies
      needs: setup
      run: npm outdated || true
