name: Run Unit Tests

on:
  workflow_call:

jobs:
  test:
    uses: ./.github/actions/setup.yml
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Run Unit Tests
      run: npm run test
