name: Run Unit Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Setup
      uses: ./.github/actions/setup.yml

    - name: Run Unit Tests
      needs: setup
      run: npm run test
