name: Typescript Compilation Check

on:
  workflow_call:

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
    - name: Setup
      uses: ./.github/actions/setup.yml

    - name: Run TypeScript Build Check
      needs: setup
      run: npm run build:check
