name: Merge to Master Pipeline

on:
  workflow_run:
    workflows: ["Check Code Quality"]
    types:
      - completed
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ vars.DEFAULT_NODE_VERSION }}
        cache: 'npm'
    - name: Install Deps
      run: npm ci
    - name: Build Application
      run: npm run build
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: ./dist
        retention-days: 1


