name: CI/CD Pipeline

on:
  workflow_run:
    workflows: ["Code Quality"]
    types:
      - completed
    branches: [master]
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    uses: ./.github/actions/setup.yml

  # tag:
  #   name: Tag Release
  #   needs: setup
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Create Release Tag
  #       run: |
  #         npm version patch
  #         git tag -a $(npm pkg get version | tr -d \") -m "Release version $(npm pkg get version | tr -d \")"
  #         git push origin $(npm pkg get version | tr -d \")

  # build:
  #   name: Build
  #   needs: setup
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Build Application
  #     run: npm run build

  #   - name: Upload Build Artifacts
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: build-artifacts
  #       path: ./dist
  #       retention-days: 1


