name: Code Quality

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ vars.DEFAULT_NODE_VERSION }}
        cache: 'npm'
    - name: Install Deps
      run: npm ci

  build-check:
    name: Compile Check
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - run: npm run build:check

  lint-check:
    name: Lint Check
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - run: npm run lint

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - run: npm run test

  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - run: npm run format:check

  audit-check:
    name: Audit Check
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - run: npm run audit -- --audit-level=moderate

  outdated-check:
    name: Outdated Check
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - run: npm outdated
